### ISSUE TITLE
Full Fire Protection 4 enchantments on armor cause infinite stacking yellow hearts when standing in lava

### ISSUE THREAD

**Issue by EvionFox** [AmyMialeeMods/no-enchant-cap#35] opened 2023-02-03 23:49 UTC
As per the description -

Game/File versions:
Minecraft version 1.19.2
Fabric API 0.73.2
No Enchant Cap 2.2.4

We discovered on our server that wearing a set of armor with fire protection enchantments causes each "tick" of damage to actually add on yellow hearts which continue to stack over time with no limit.

At first we thought this might be a compatibility issue with Mythic Metals armors, but after some testing, the same effect happens when the enchantments are on vanilla Minecraft netherite armor.

The tests:
Fire Prot 4 enchants:
Only 1 piece of armor - take damage, lose hearts
2 pieces - neutral damage, get the damage tick animation, but no heart loss
3 pieces - slow yellow heart increase with each tick
4 pieces - faster yellow heart increase with ticks

Fire Prot 3 enchants:
1 and 2: take damage
3 armor pieces: Neutral damage, just animation
4 armor set: Slow increase of yellow hearts over time.

Here is a client log in case it would help, but I didn't see any stand-out errors. 
[latest.txt](https://github.com/AmyMialeeMods/no-enchant-cap/files/10583637/latest.txt)

**Comment by AmyMialee** [comment] 2023-02-04 02:12
dupe of #32

**Comment by AmyMialee** [comment] 2023-02-04 02:12
and #34

**Closed by AmyMialee** 2023-02-04 02:12 UTC
